trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -e ".[testing,docs,singularity,cwl,docker,snakemake]"
  displayName: 'Install all dependencies'

- script:
    make html
  workingDirectory: docs
  displayName: 'Build documentation'

#- script:
#    conda create --quiet --file bwa_env.yaml
#    dataprov -i genome.fa -o genome.fa.bwt run bwa index genome.fa
#    mkdir mapped_reads
#    dataprov -i genome.fa.bwt -i samples/A.fastq -o mapped_reads/A.bam run \
#      'bwa mem genome.fa samples/A.fastq > mapped_reads/A.bam'
#  workingDirectory: examples/bwa
#  displayName: 'Create conda envianment for integration tests'

#- script:
#    conda env create --quiet --file environment.yml
#    dataprov -i examples/bwa/genome.fa -o examples/bwa/genome.fa.bwt run bwa index examples/bwa/genome.fa
#  displayName: 'indexExample'