# Stubs for prov.dot (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

__email__: str
GENERIC_NODE_STYLE: Any
DOT_PROV_STYLE: Any
ANNOTATION_STYLE: Any
ANNOTATION_LINK_STYLE: Any
ANNOTATION_START_ROW: str
ANNOTATION_ROW_TEMPLATE: str
ANNOTATION_END_ROW: str

def htlm_link_if_uri(value: Any): ...
def prov_to_dot(
    bundle: Any,
    show_nary: bool = ...,
    use_labels: bool = ...,
    direction: str = ...,
    show_element_attributes: bool = ...,
    show_relation_attributes: bool = ...,
): ...
