# Stubs for prov.tests.test_json (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest
from typing import Any

from prov.tests.test_model import AllTestsBase
from prov.tests.utility import RoundTripTestCase

logger: Any

class TestJSONSerializer(unittest.TestCase):
    def test_decoding_unicode_value(self) -> None: ...

class RoundTripJSONTests(RoundTripTestCase, AllTestsBase):
    FORMAT: str = ...
