# Stubs for prov.tests.utility (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest
from typing import Any, Optional

logger: Any

class DocumentBaseTestCase(unittest.TestCase):
    def do_tests(self, prov_doc: Any, msg: Optional[Any] = ...) -> None: ...

class RoundTripTestCase(DocumentBaseTestCase):
    FORMAT: Any = ...
    def do_tests(self, prov_doc: Any, msg: Optional[Any] = ...) -> None: ...
    def assertRoundTripEquivalence(self, prov_doc: Any, msg: Optional[Any] = ...) -> None: ...
