# Stubs for prov.serializers.provn (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from prov.serializers import Serializer

__email__: str
logger: Any

class ProvNSerializer(Serializer):
    def serialize(self, stream: Any, **kwargs: Any) -> None: ...
    def deserialize(self, stream: Any, **kwargs: Any) -> None: ...
